---
title: "homework 5"
output: html_document
date: '2022-05-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidymodels)
library(tidyverse)
library(ggplot2)
library(ISLR)
library(ISLR2)
library(tidyverse)
library(glmnet)
tidymodels_prefer()
```

## Question 1

```{r}
library(janitor)

pokemon_og <- read.csv("~/Downloads/homework-5/data/pokemon.csv")

pokemon <- clean_names(pokemon_og)
```
The clean_names() function cleans names of the data frame and the resulting names are unique and consist only of the _ character, numbers, and letters. It is useful because the data frame is more organized and clean. 

## Question 2 

```{r}
pokemon %>% 
  ggplot(aes(x = type_1)) +
  geom_bar()
```

There are 18 classes. There are a few Pokemon with only a few Pokemon in their class, such as Flying and Fairy. 

```{r}
classes <- c('Bug', 'Fire', 'Grass', 'Normal', 'Water', 'Psychic')

pokemon <- filter(pokemon, type_1 %in% classes)

pokemon$type_1 <- factor(pokemon$type_1)
pokemon$legendary <- factor(pokemon$legendary)
```

